### ISSUE TITLE
No longer compatible with Node v0.1.31-3

### ISSUE THREAD

**Issue by bentruyman** [persvr/jsgi-node#1]
As expected, Node has a number of changes to its internals like the removal of promises.

**Comment by kriszyp** [comment]
Do you have a specific reproducible test case? jsgi-node on 0.1.31 seems to be working fine for me.

**Comment by bentruyman** [comment]
I apologize...my issue description probably wasn't all that helpful.

Firstly, I found I wasn't using jsgi-node HEAD.  Although, after updating, I'm finding my application complaining about not being able to find the "promise" module.  Is this a module you're expecting Node to provide, or is this a third-party module I'm missing?

Thanks for all the great work you're doing.

**Comment by bentruyman** [comment]
Not an issue...I was missing 'node-promise'.

**Comment by kriszyp** [comment]
Hmm, that's right, it is dependent on node-promise now. I guess I should make that clear in the docs, or try to remove the dependency.
